disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - sorted_imports
  - operator_usage_whitespace
  - explicit_self

indentation: 2

line_length:
  warning: 120
  error: 200

file_length:
  warning: 400
  error: 1000

excluded:
  - Pods
  - DerivedData
  - .build
