disabled_rules:
  - vertical_whitespace
  - comment_spacing
  - multiple_closures_with_trailing_closure
  - duplicate_imports

included:
  - RickAndMorty
excluded:
  - Pods
  - DerivedData

line_length:
  warning: 120
  error: 200

function_body_length:
  warning: 50
  error: 100
