# Конфигурация правил SwiftLint
excluded:
  - Pods
  - DerivedData

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - missing_docs
  - file_length

line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 400
  error: 1000

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 20
