name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      # Show Xcode version and available destinations
      - name: Show Xcode info
        run: |
          xcodebuild -version
          xcodebuild -showsdks
          xcrun simctl list devices available

      - name: Build
        env:
          scheme: RickAndMorty
          platform: iOS Simulator
        run: |
          # Find a valid simulator
          device=`xcrun simctl list devices available iPhone | grep -v '^--' | grep -v '^ --' | head -1 | sed -E 's/(.+)\((.+)\)/\2/'`
          # Build
          xcodebuild build -project RickAndMorty.xcodeproj -scheme "$scheme" -destination "platform=$platform,id=$device" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
