name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-13

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Setup Xcode version
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      # Step 3: Clean DerivedData
      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      # Step 4: Build project
      - name: Build Project
        run: |
          xcodebuild -scheme "RickAndMorty" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max,OS=17.2' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            clean build \
            | xcpretty

      # Step 5: Archive artifacts
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ~/Library/Developer/Xcode/DerivedData
