name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Show build settings
        run: |
          xcodebuild -showBuildSettings -scheme "RickAndMorty"

      - name: Show available schemes
        run: |
          xcodebuild -list

      - name: Build
        run: |
          xcodebuild build -scheme "RickAndMorty" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
