name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      # Clean build artifacts
      - name: Clean Build Folder
        run: |
          xcodebuild clean -scheme "RickAndMorty"

      # Build the project
      - name: Build Project
        run: |
          xcodebuild build \
            -scheme "RickAndMorty" \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO
