name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-13

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout
        uses: actions/checkout@v3

      # Шаг 2: Установка Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      # Шаг 3: Очистка DerivedData
      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      # Шаг 4: Сборка проекта
      - name: Build Project
        run: |
          xcodebuild -scheme "RickAndMorty" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            clean build \
            | xcpretty
